[FIX] doesn't crash when there is no 'banned' file

diff --git a/.github/workflows/checker.yml b/.github/workflows/checker.yml
--- a/.github/workflows/checker.yml
+++ b/.github/workflows/checker.yml
@@ -43,24 +43,23 @@ jobs:
       - name: Check Functions
         id: func
         run: |
-          FILE=1
           if [ ! -f "$BANNED_FUNC_FILE" ]; then
               echo "::warning file:${BANNED_FUNC_FILE}::Le fichier $BANNED_FUNC_FILE n'existe pas."
-              FILE=0
+          else
+              while IFS= read -r function || [ -n "$function" ]; do
+                  if [[ -z "$function" || "$function" =~ ^# ]]; then
+                      continue
+                  fi
+                  FOUND=$(grep -rn --include="*.c" "\b$function\b" "$SOURCE_DIR" 2>/dev/null | sed 's/: .*$//')
+                  if [ -n "$FOUND" ]; then
+                      while IFS= read -r location; do
+                          echo "::error file=${location}::${function} is a banned function !"
+                      done <<< "$FOUND"
+                      echo "banned_func=true" >> $GITHUB_OUTPUT
+                      exit 1
+                  fi
+              done < "$BANNED_FUNC_FILE"
           fi
-          while FILE == 1 && IFS= read -r function || [ -n "$function" ]; do
-              if [[ -z "$function" || "$function" =~ ^# ]]; then
-                  continue
-              fi
-              FOUND=$(grep -rn --include="*.c" "\b$function\b" "$SOURCE_DIR" 2>/dev/null | sed 's/: .*$//')
-              if [ -n "$FOUND" ]; then
-                  while IFS= read -r location; do
-                      echo "::error file=${location}::${function} is a banned function !"
-                  done <<< "$FOUND"
-                  echo "banned_func=true" >> $GITHUB_OUTPUT
-                  exit 1
-              fi
-          done < "$BANNED_FUNC_FILE"
           echo "banned_func=false" >> $GITHUB_OUTPUT
 
   check_coding_style:
